POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe",
  "email": "popopopopo99@example.com",
  "address": "Jakarta",
  "dateOfBirth": "1990-01-01",
  "registeredDate": "2025-12-15"
}